# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wgmesh < Formula
  desc "WireGuard mesh network — decentralized peer discovery and encrypted networking"
  homepage "https://github.com/atvirokodosprendimai/wgmesh"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atvirokodosprendimai/wgmesh/releases/download/v0.2.0/wgmesh_0.2.0_darwin_amd64.tar.gz"
      sha256 "8b9add325db310a9146adf456f6888dae2c9ba57b9be6fa652804a63ff69a3f3"

      define_method(:install) do
        bin.install "wgmesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atvirokodosprendimai/wgmesh/releases/download/v0.2.0/wgmesh_0.2.0_darwin_arm64.tar.gz"
      sha256 "6583240e91561b735d37a725fe09dcc24d2ff799f4fa506fc426183eead91435"

      define_method(:install) do
        bin.install "wgmesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/atvirokodosprendimai/wgmesh/releases/download/v0.2.0/wgmesh_0.2.0_linux_amd64.tar.gz"
      sha256 "e22456b5326d51db55f7fc000cd5d11ec82ad9e5194d62f10fa463bcde38d0f9"
      define_method(:install) do
        bin.install "wgmesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atvirokodosprendimai/wgmesh/releases/download/v0.2.0/wgmesh_0.2.0_linux_arm64.tar.gz"
      sha256 "ae28389dc1baa3cb842f8f0915fad25aaf0aa9833c826a8064869eaaa18f526a"
      define_method(:install) do
        bin.install "wgmesh"
      end
    end
  end

  test do
    system "#{bin}/wgmesh", "version"
  end
end
